version: '3.7'

services:
  dm8:
    image: dm8_single:v8.1.2.128_ent_x86_64_ctm_pack4
    ports:
      - 5236:5236
    privileged: true
    restart: unless-stopped
    environment:
      - PAGE_SIZE=16
      - LD_LIBRARY_PATH=/opt/dmdbms/bin
      - INSTANCE_NAME=dm8_01
    volumes:
      - "./data:/opt/dmdbms/data"
    